# Generated by Django 4.2.3 on 2023-08-11 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomforest', '0002_celllines_uploadedfolder_cellline'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastTrainingResultsRandomForest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('roc_curve_image', models.ImageField(blank=True, null=True, upload_to='roc_curves/')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadedfolder',
            name='cellline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='randomforest.celllines'),
        ),
    ]
