# Generated by Django 4.2.3 on 2023-08-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomforest', '0003_lasttrainingresultsrandomforest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasttrainingresultsrandomforest',
            name='accuracy',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
