# Generated by Django 4.2.3 on 2023-08-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomforest', '0005_lasttrainingresultskfda'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasttrainingresultskfda',
            name='number_of_cells',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lasttrainingresultsrandomforest',
            name='number_of_cells',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
