# Generated by Django 4.2.3 on 2023-08-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0006_lasttrainingresultskfda_number_of_cells_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lasttrainingresultskfda",
            name="class_report",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="class_report",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
