# Generated by Django 4.2.3 on 2023-08-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0007_lasttrainingresultskfda_class_report_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lasttrainingresultskfda",
            name="matrix_data",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="matrix_data",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
