# Generated by Django 4.2.3 on 2023-08-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0008_lasttrainingresultskfda_matrix_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lasttrainingresultskfda",
            name="class_report",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lasttrainingresultskfda",
            name="matrix_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
