# Generated by Django 4.2.3 on 2023-08-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0009_alter_lasttrainingresultskfda_class_report_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="graph",
            field=models.CharField(default=1, max_length=50000),
            preserve_default=False,
        ),
    ]
