# Generated by Django 4.2.3 on 2023-08-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0010_lasttrainingresultsrandomforest_graph"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lasttrainingresultsrandomforest",
            old_name="graph",
            new_name="confusion_matrix_graph",
        ),
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="roc_curve_graph",
            field=models.CharField(default=1, max_length=50000),
            preserve_default=False,
        ),
    ]
