# Generated by Django 4.2.3 on 2023-08-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "randomforest",
            "0011_rename_graph_lasttrainingresultsrandomforest_confusion_matrix_graph_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lasttrainingresultskfda",
            name="confusion_matrix_graph",
            field=models.CharField(default=1, max_length=50000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultskfda",
            name="roc_curve_graph",
            field=models.CharField(default=1, max_length=50000),
            preserve_default=False,
        ),
    ]
