# Generated by Django 4.2.3 on 2023-08-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "randomforest",
            "0012_lasttrainingresultskfda_confusion_matrix_graph_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="feature_importance_curve_graph",
            field=models.CharField(default=1, max_length=50000),
            preserve_default=False,
        ),
    ]
