# Generated by Django 4.2.3 on 2023-08-16 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "randomforest",
            "0013_lasttrainingresultsrandomforest_feature_importance_curve_graph",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfolder",
            name="cellline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="randomforest.celllines"
            ),
        ),
    ]
