# Generated by Django 4.2.3 on 2023-08-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0015_alter_uploadedfolder_cellline"),
    ]

    operations = [
        migrations.AddField(
            model_name="lasttrainingresultskfda",
            name="feature_importance_curve_graph",
            field=models.CharField(default=1, max_length=50000),
            preserve_default=False,
        ),
    ]
