# Generated by Django 4.2.3 on 2023-08-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0016_lasttrainingresultskfda_feature_importance_curve_graph"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_objects",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "current_segment",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("progress", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "kfda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="randomforest.lasttrainingresultskfda",
                    ),
                ),
                (
                    "random_forest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="randomforest.lasttrainingresultsrandomforest",
                    ),
                ),
            ],
        ),
    ]
