# Generated by Django 4.2.3 on 2023-08-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0017_analysisrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="learning_curve_graph",
            field=models.CharField(default=1, max_length=50000),
            preserve_default=False,
        ),
    ]
