# Generated by Django 4.2.3 on 2023-08-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0018_lasttrainingresultsrandomforest_learning_curve_graph"),
    ]

    operations = [
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="class_distribution_curve_uri",
            field=models.CharField(default=1, max_length=50000),
            preserve_default=False,
        ),
    ]
