# Generated by Django 4.2.3 on 2023-08-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0020_lasttrainingresultskfda_learning_curve_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="comp_options",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="param_options",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
