# Generated by Django 4.2.3 on 2023-08-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0021_analysisrun_comp_options_analysisrun_param_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="celllines",
            field=models.ManyToManyField(
                blank=True, null=True, to="randomforest.celllines"
            ),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="cellnum",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
