# Generated by Django 4.2.3 on 2023-08-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0022_analysisrun_celllines_analysisrun_cellnum"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lasttrainingresultskfda",
            old_name="feature_importance_curve_graph",
            new_name="centroiduri",
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="stage",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
