# Generated by Django 4.2.3 on 2023-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "randomforest",
            "0023_rename_feature_importance_curve_graph_lasttrainingresultskfda_centroiduri_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="inProgress",
            field=models.BooleanField(default=True),
        ),
    ]
