# Generated by Django 4.2.3 on 2023-08-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0024_analysisrun_inprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisrun",
            name="inProgress",
            field=models.BooleanField(default=False),
        ),
    ]
