# Generated by Django 4.2.3 on 2023-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0025_alter_analysisrun_inprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="lasttrainingresultskfda",
            name="class_seperation_uri",
            field=models.CharField(default=1, max_length=50000),
            preserve_default=False,
        ),
    ]
