# Generated by Django 4.2.3 on 2023-08-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0026_lasttrainingresultskfda_class_seperation_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="email",
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
