# Generated by Django 4.2.3 on 2023-08-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0027_analysisrun_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lasttrainingresultsrandomforest",
            name="class_distribution_curve_uri",
            field=models.CharField(max_length=500000),
        ),
        migrations.AlterField(
            model_name="lasttrainingresultsrandomforest",
            name="confusion_matrix_graph",
            field=models.CharField(max_length=500000),
        ),
        migrations.AlterField(
            model_name="lasttrainingresultsrandomforest",
            name="feature_importance_curve_graph",
            field=models.CharField(max_length=500000),
        ),
        migrations.AlterField(
            model_name="lasttrainingresultsrandomforest",
            name="learning_curve_graph",
            field=models.CharField(max_length=500000),
        ),
        migrations.AlterField(
            model_name="lasttrainingresultsrandomforest",
            name="roc_curve_graph",
            field=models.CharField(max_length=500000),
        ),
    ]
