# Generated by Django 4.2.3 on 2023-08-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "randomforest",
            "0028_alter_lasttrainingresultsrandomforest_class_distribution_curve_uri_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
