# Generated by Django 4.2.3 on 2023-08-30 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0029_analysisrun_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="objectnum",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysisrun",
            name="kfda",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                to="randomforest.lasttrainingresultskfda",
            ),
        ),
        migrations.AlterField(
            model_name="analysisrun",
            name="random_forest",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="randomforest.lasttrainingresultsrandomforest",
            ),
        ),
    ]
