# Generated by Django 4.2.3 on 2023-08-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0030_analysisrun_objectnum_alter_analysisrun_kfda_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="X_data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
