# Generated by Django 4.2.3 on 2023-08-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0031_analysisrun_x_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="y_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lasttrainingresultskfda",
            name="centroiduri",
            field=models.CharField(max_length=500000),
        ),
        migrations.AlterField(
            model_name="lasttrainingresultskfda",
            name="class_seperation_uri",
            field=models.CharField(max_length=500000),
        ),
        migrations.AlterField(
            model_name="lasttrainingresultskfda",
            name="confusion_matrix_graph",
            field=models.CharField(max_length=500000),
        ),
        migrations.AlterField(
            model_name="lasttrainingresultskfda",
            name="learning_curve_uri",
            field=models.CharField(max_length=500000),
        ),
        migrations.AlterField(
            model_name="lasttrainingresultskfda",
            name="roc_curve_graph",
            field=models.CharField(max_length=500000),
        ),
    ]
