# Generated by Django 4.2.3 on 2023-08-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0032_analysisrun_y_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="objectId_data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
