# Generated by Django 4.2.3 on 2023-08-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randomforest", "0033_analysisrun_objectid_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="features",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysisrun",
            name="objectId_data",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
