# Generated by Django 4.2.3 on 2023-09-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "randomforest",
            "0035_rename_accuracy_lasttrainingresultskfda_dpg_accuracy_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="lasttrainingresultskfda",
            old_name="dpg_class_report",
            new_name="class_report",
        ),
        migrations.RenameField(
            model_name="lasttrainingresultskfda",
            old_name="class_seperation_uri",
            new_name="dpg_class_seperation_uri",
        ),
        migrations.RenameField(
            model_name="lasttrainingresultskfda",
            old_name="learning_curve_uri",
            new_name="dpg_learning_curve_uri",
        ),
        migrations.AddField(
            model_name="lasttrainingresultskfda",
            name="npg_class_seperation_uri",
            field=models.CharField(default=1, max_length=500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultskfda",
            name="npg_learning_curve_uri",
            field=models.CharField(default=1, max_length=500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultskfda",
            name="opg_class_seperation_uri",
            field=models.CharField(default=1, max_length=500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultskfda",
            name="opg_learning_curve_uri",
            field=models.CharField(default=1, max_length=500000),
            preserve_default=False,
        ),
    ]
