# Generated by Django 4.2.3 on 2023-09-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "randomforest",
            "0036_rename_dpg_class_report_lasttrainingresultskfda_class_report_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="all_params_accuracy",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="all_params_confusion_matrix_graph",
            field=models.CharField(default=1, max_length=500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="all_params_feature_importance_curve_graph",
            field=models.CharField(default=1, max_length=500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="dpg_npg_accuracy",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="dpg_npg_confusion_matrix_graph",
            field=models.CharField(default=1, max_length=500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="dpg_opg_accuracy",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="dpg_opg_confusion_matrix_graph",
            field=models.CharField(default=1, max_length=500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="dpg_opg_feature_importance_curve_graph",
            field=models.CharField(default=1, max_length=500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="npg_dpg_feature_importance_curve_graph",
            field=models.CharField(default=1, max_length=500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="npg_opg_confusion_matrix_graph",
            field=models.CharField(default=1, max_length=500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="npg_opg_feature_importance_curve_graph",
            field=models.CharField(default=1, max_length=500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lasttrainingresultsrandomforest",
            name="opg_npg_accuracy",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
